"use client";

import Link from "next/link";
import "./globals.css";
import { usePathname } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LINKS = [
  { href: "/", label: "Home" },
  { href: "/products/add", label: "Create Product" },
] as const;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body>
        <header className="p-5  shadow-md ">
          <nav className="max-w-7xl mx-auto">
            <ul className="flex items-center gap-4">
              {LINKS.map(({ href, label }) => (
                <li
                  key={href}
                  className={`${
                    pathname === href ? "text-blue-600" : "text-gray-600"
                  } font-semibold hover:underline`}
                >
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
